# Generated by Django 2.2.11 on 2020-05-21 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='description')),
                ('sql', models.TextField(blank=True, verbose_name='sql')),
                ('url', models.CharField(blank=True, max_length=1000, verbose_name='url')),
                ('view', models.CharField(blank=True, max_length=1000, verbose_name='view')),
                ('form', models.CharField(blank=True, max_length=500, verbose_name='form')),
                ('parameters', models.CharField(blank=True, max_length=4000, verbose_name='parameters')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Category')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'ordering': ('name',),
            },
        ),
    ]
